version: '3.9'

services:
  pgpool2:
    image: 'pgpool/pgpool:4.0.23'
    ports:
      - 7000:7000
    environment:
      PGPOOL_PARAMS_PORT: 7000
      PGPOOL_PARAMS_BACKEND_HOSTNAME0: pg-master
      PGPOOL_PARAMS_BACKEND_PORT0: 5432
      PGPOOL_PARAMS_BACKEND_WEIGHT0: 0
      PGPOOL_PARAMS_BACKEND_DATA_DIRECTORY0: tmp/master/
      PGPOOL_PARAMS_BACKEND_HOSTNAME1: pg-slave1
      PGPOOL_PARAMS_BACKEND_PORT1: 5433
      PGPOOL_PARAMS_BACKEND_WEIGHT1: 1
      PGPOOL_PARAMS_BACKEND_DATA_DIRECTORY1: tmp/slave1/
      PGPOOL_PARAMS_BACKEND_HOSTNAME2: pg-slave2
      PGPOOL_PARAMS_BACKEND_PORT2: 5434
      PGPOOL_PARAMS_BACKEND_WEIGHT2: 2
      PGPOOL_PARAMS_BACKEND_DATA_DIRECTORY2: tmp/slave2/
      PGPOOL_PARAMS_SR_CHECK_USER: repuser
      PGPOOL_PARAMS_SR_CHECK_PASSWORD: repuser
      PGPOOL_PARAMS_HEALTH_CHECK_PERIOD: 10
      PGPOOL_PARAMS_HEALTH_CHECK_USER: repuser
      PGPOOL_PARAMS_HEALTH_CHECK_PASSWORD: repuser
      PGPOOL_PARAMS_ENABLE_POOL_HBA: 'on'
      PGPOOL_PARAMS_ENABLE_POOL_PASSWD: /opt/pgpool-II/etc/pool_passwd
      PGPOOL_PCP_USER: myadminuser
      PGPOOL_PCP_PASSWORD: mypassword
    volumes:
      - ./pgpool.conf:/opt/pgpool-II/etc/pgpool.conf
      - ./pool_hba.conf:/opt/pgpool-II/etc/pool_hba.conf
      - ./pool_passwd:/opt/pgpool-II/etc/pool_passwd

  pg-master:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    environment:
      P_MASTER: P_MASTER
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      REPLICA_POSTGRES_USER: repuser
      REPLICA_POSTGRES_PASSWORD: repuser
      REPLICATE_TO: pg-slave1
      REPLICATE_TO2: pg-slave2
      REPLICA_NAME: r1
      REPLICA_NAME2: r2
      SYNCHRONOUS_COMMIT: 'off'
      PGDATA: /var/lib/postgresql/data/pgdata

  pg-slave1:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5433:5432
    environment:
      P_SLAVE1: P_SLAVE1
      POSTGRES_USER: repuser
      POSTGRES_PASSWORD: repuser
      REPLICA_NAME: r1
      REPLICATE_FROM: pg-master
      PGDATA: /var/lib/postgresql/data/pgdata

  pg-slave2:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5434:5432
    environment:
      P_SLAVE2: P_SLAVE2
      POSTGRES_USER: repuser
      POSTGRES_PASSWORD: repuser
      REPLICA_NAME2: r2
      REPLICATE_FROM: pg-master
      PGDATA: /var/lib/postgresql/data/pgdata
